version: '3'

services:
  db:
    image: mariadb
    environment:
      TZ: America/Toronto
      MYSQL_ROOT_PASSWORD: example
    restart: unless-stopped

  app:
    image: technicallyreal/tan-lools
    environment:
      TZ: America/Toronto
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASS: example
      DATABASE_NAME: app
      DISCORD_CLIENT_ID:
      DISCORD_CLIENT_SECRET:
      DISCORD_TOKEN:
      DISCORD_CALLBACK_URL: http://localhost:3000/callback
      DISCORD_SERVER_ID:
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped
