version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    restart: unless-stopped

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: unless-stopped

  app:
    build: ./
    environment:
      NODE_ENV: production
      DBHOST: 'db'
      # BASEURL: 'test'
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped
