version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    # network_mode: host
    restart: unless-stopped

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    # network_mode: host
    restart: unless-stopped

  app:
    build: ./
    volumes:
      - ..:/usr/src/app:cached
      - ~/.ssh:/home/node/.ssh
    environment:
      NODE_ENV: development
      DBHOST: 'db'
      # BASEURL: 'test'
    depends_on:
      - db
    ports:
      - "3000:3000"
    # network_mode: host
    command: sleep infinity
    restart: unless-stopped
