version: '3'

services:
  db:
    image: mariadb
    environment:
      TZ: America/Toronto
      MYSQL_ROOT_PASSWORD: example
    restart: unless-stopped

  adminer:
    image: adminer
    depends_on:
      - db
    environment:
      TZ: America/Toronto
    ports:
      - 8080:8080
    restart: unless-stopped

  app:
    image: node:16.6.0
    volumes:
      - ..:/usr/src/app:cached
      - ~/.ssh:/home/node/.ssh
    env_file:
      - .env
    environment:
      TZ: America/Toronto
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: sleep infinity
    restart: unless-stopped
